### ISSUE TITLE
DBM-PvP/Ashenvale.lua:1: attempt to compare nil with number

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [DeadlyBossMods/DBM-PvP#130]
**Describe the bug**
DBM-PvP/Ashenvale.lua:1: attempt to compare nil with number**

**Do you have an error log of what happened?**
```
1x DBM-PvP/Ashenvale.lua:1: attempt to compare nil with number
[string "@DBM-PvP/Ashenvale.lua"]:1: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@DBM-Core/DBM-Core.lua"]:3916: in function `LoadMod'
[string "@DBM-Core/DBM-Core.lua"]:3861: in function `LoadModsOnDemand'
[string "@DBM-Core/DBM-Core.lua"]:3826: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1113: in function <DBM-Core/DBM-Core.lua:1100>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare nil with number"
```
**To Reproduce**
1. Go to Ashenvale in classic era

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
no

**Which version of DeadlyBossMods are you using?**
11.15.9

**Was it working in a previous version? If yes, which was the last good one?**
IDK

**Additional context**
Ashenvale isn't a pvp zone in classic era

**Comment by emmericp** [comment]
Thanks for reporting!

Looks like there are two distinct bugs here:

1) PvP mod being loaded in Ashenvale in non-SoD
2) Ashenvale mod throwing an error in non-SoD

(1) is a bit more annoying to fix (and I was aware of this issue when I wrote the loading logic) because the loading logic is based on information in the toc, not based on code in the pvp mod (as its, well, not loaded). I'm probably going to address this somehow in Core once more PvP zones land in SoD

(2) is fixed in #131, the mod should just quietly pretend to not exist outside of SoD
