### ISSUE TITLE
DBM-PvP missing data (Comp Stomp Brawl)

### ISSUE THREAD

**Issue by markdall** [DeadlyBossMods/DBM-PvP#19]
Expected: DBM-PVP works normally in the "Comp Stomp" brawl which is Arathi Basin vs. Bots.

Actual: Doesn't work, gives the following message. 

`<DBM> DBM-PvP missing data, please report to our discord. (A,60,5,1000) `

I don't want to join a discord server in order to report missing data

**To Reproduce**
1. Join the Comp Stomp Brawl.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

No, and I'm not going to. I don't really need this fixed, I just wanted to help out and report it.

**Which version of DeadlyBossMods are you using?**
`DBM 8.3.19 (2020/03/31 14:09:21) / VPVEM: v10`

**Comment by QartemisT** [comment]
For now, we do not support Comp Stomp, but I may add support at a later date if/when it comes around again. This is mainly down to the point calculations being very "unique" and calculate differently under a seperate calculation rather than points owned.

Sorry for any inconvenience. Leaving this open for future reference =]

**Comment by QartemisT** [comment]
Being tracked now by #20.

Going to be sanity checking every brawl, and work out their score systems :)
